app_id: "164daba7-0604-4efc-8622-121f098123f6"
app_secret: "yfUXGX334}=ifyirBUD63()"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read files.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
